SELECT a.Name, r.Count
FROM
(
SELECT REVERSE(SUBSTRING_INDEX(REVERSE(SUBSTRING_INDEX(AgentCode, '-', 2)), '-', 1)) AS AgentId, COUNT(Id) AS Count
FROM Member
WHERE REVERSE(SUBSTRING_INDEX(REVERSE(SUBSTRING_INDEX(AgentCode, '-', 2)), '-', 1)) != ''
AND Status != 2
AND AddTime >= ? AND AddTime <= ?
GROUP BY REVERSE(SUBSTRING_INDEX(REVERSE(SUBSTRING_INDEX(AgentCode, '-', 2)), '-', 1))
) AS r
JOIN Agent AS a ON a.Id = r.AgentId
